const lineStatusType = {
  FETCH_LINE_STATUS_FINISH: 'FETCH_LINE_STATUS_FINISH',
  FETCH_LINE_STATUS_ERROR: 'FETCH_LINE_STATUS_ERROR',
  UPDATE_LINE_STATUS_DATA: 'UPDATE_LINE_STATUS_DATA',
  CLEAR_LINE_STATUS_DATA: 'CLEAR_LINE_STATUS_DATA',
  CLEAR_FETCH_STATUS: 'CLEAR_FETCH_STATUS'
};

export default lineStatusType;
